"""
Audit manifest models for phase 18.B.

AuditTask describes what checks the closure-checker must perform for a given
requirement. AuditResult captures the outcome of each check.

The orchestrator builds the manifest (list of AuditTask) via code rules,
ensuring deterministic audit scope. The closure-checker only executes the
checks listed in the manifest — it does not decide which requirements to audit.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


CheckType = Literal[
    "verdict_vs_code",
    "findings_anti_hallucination",
    "prescriptive_boundary_self_check",
]


class AuditTask(BaseModel):
    """One requirement's audit specification generated by the orchestrator.

    The orchestrator's build_audit_manifest() decides which requirements to
    audit and what checks each needs. The closure-checker executes each task.
    """

    requirement_id: str = Field(
        description="The requirement id (e.g. 'req-014').",
    )
    reasons: list[str] = Field(
        default_factory=list,
        description=(
            "Why this requirement is in the audit manifest. Examples: "
            "'non_compliant_defect', 'new_interface_origin', 'overlap_group', "
            "'findings_has_backtick_tokens', 'findings_has_prescriptive'."
        ),
    )
    cited_locations: list[str] = Field(
        default_factory=list,
        description=(
            "evidence_locations from the requirement, to be opened by "
            "the closure-checker."
        ),
    )
    checks_required: list[CheckType] = Field(
        default_factory=list,
        description=(
            "Which semantic checks to perform. Subset of: "
            "{verdict_vs_code, findings_anti_hallucination, "
            "prescriptive_boundary_self_check}."
        ),
    )


class AuditResult(BaseModel):
    """Outcome of auditing one requirement.

    The closure-checker fills per_check with PASS/FAIL/SKIPPED for each
    check_type listed in the corresponding AuditTask.checks_required.
    """

    requirement_id: str = Field(
        description="The audited requirement id.",
    )
    per_check: dict[CheckType, Literal["PASS", "FAIL", "SKIPPED"]] = Field(
        default_factory=dict,
        description=(
            "Outcome for each check type. Keys match the task's checks_required."
        ),
    )
    evidence_opened: list[str] = Field(
        default_factory=list,
        description=(
            "File:range entries that the closure-checker actually Read. "
            "Used for cost tracking and debugging."
        ),
    )
    failures: list[str] = Field(
        default_factory=list,
        description=(
            "For each FAIL, a one-line explanation of what went wrong. "
            "Example: 'findings claims `db.mget` exists but Read of "
            "src/database/redis/main.js:1-100 shows no such function'."
        ),
    )


class AuditManifest(BaseModel):
    """The full audit plan sent to closure-checker.

    Generated by build_audit_manifest() in the orchestrator; consumed by
    the closure-checker, which must produce an AuditResult for each task.
    """

    tasks: list[AuditTask] = Field(
        default_factory=list,
        description="Audit tasks for each requirement that needs checking.",
    )
    warnings: list[str] = Field(
        default_factory=list,
        description=(
            "I1/I3 structural invariant warnings (from check_structural_invariants) "
            "that the closure-checker should be aware of but does not need to act on."
        ),
    )