"""Phase4 patch planner worker implementation."""

from __future__ import annotations

from typing import Any, Dict

from .workers._common import load_json, resolve_instance_dir, save_json


def create_patch_plan(workspace_dir: str, instance_id: str) -> Dict[str, Any]:
    instance_dir = resolve_instance_dir(workspace_dir, instance_id)
    closure_path = instance_dir / "closure" / "closure_report.json"
    if not closure_path.exists():
        raise FileNotFoundError("closure_report.json missing")

    closure = load_json(closure_path)
    if not closure.get("passed", False):
        raise RuntimeError("closure check not passed")

    plan = {
        "instance_id": instance_id,
        "edits": [
            {
                "file_path": "repo/placeholder.py",
                "change_type": "modify",
                "description": "placeholder patch generated by planner",
            }
        ],
    }
    save_json(instance_dir / "plan" / "patch_plan.json", plan)
    return plan
